export type MealCategory = 'breakfast' | 'lunch' | 'dinner';

export type Recipe = {
  id: string;
  title: string;
  description: string;
  image: string;
  cookingTime: number; // in minutes
  servings: number;
  difficulty: 'easy' | 'medium' | 'hard';
  category: MealCategory;
  ingredients: {
    name: string;
    amount: string;
  }[];
  instructions: string[];
  tips?: string[];
};

export const recipes: Recipe[] = [
  // ── BREAKFAST ──
  {
    id: '1',
    title: 'Fluffy Buttermilk Pancakes',
    description: 'Light and airy pancakes served with maple syrup, fresh berries, and a dusting of powdered sugar.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&h=300&fit=crop',
    cookingTime: 20,
    servings: 4,
    difficulty: 'easy',
    category: 'breakfast',
    ingredients: [
      { name: 'All-purpose flour', amount: '300g' },
      { name: 'Buttermilk', amount: '400ml' },
      { name: 'Eggs', amount: '2' },
      { name: 'Butter (melted)', amount: '50g' },
      { name: 'Baking powder', amount: '2 tsp' },
      { name: 'Sugar', amount: '2 tbsp' },
      { name: 'Vanilla extract', amount: '1 tsp' },
      { name: 'Salt', amount: '1/2 tsp' },
    ],
    instructions: [
      'Whisk flour, baking powder, sugar, and salt in a large bowl.',
      'In a separate bowl, mix buttermilk, eggs, melted butter, and vanilla.',
      'Pour wet ingredients into dry and stir until just combined (lumps are okay).',
      'Heat a non-stick pan over medium heat and lightly grease.',
      'Pour 1/4 cup batter per pancake and cook until bubbles form on top.',
      'Flip and cook another 1-2 minutes until golden.',
      'Serve with maple syrup, fresh berries, and powdered sugar.',
    ],
    tips: [
      'Don\'t overmix the batter — lumps make fluffier pancakes.',
      'Let batter rest 5 minutes before cooking for extra fluffiness.',
      'Keep cooked pancakes warm in a 90°C oven.',
    ],
  },
  {
    id: '2',
    title: 'Avocado & Poached Egg Toast',
    description: 'Creamy smashed avocado on sourdough topped with perfectly poached eggs and chili flakes.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&h=300&fit=crop',
    cookingTime: 15,
    servings: 2,
    difficulty: 'medium',
    category: 'breakfast',
    ingredients: [
      { name: 'Ripe avocados', amount: '2' },
      { name: 'Sourdough bread', amount: '4 slices' },
      { name: 'Eggs', amount: '4' },
      { name: 'Lemon juice', amount: '1 tbsp' },
      { name: 'Red chili flakes', amount: '1/2 tsp' },
      { name: 'White vinegar', amount: '1 tbsp' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Toast sourdough slices until golden and crispy.',
      'Mash avocados with lemon juice, salt, and pepper.',
      'Bring a pot of water to a gentle simmer and add vinegar.',
      'Crack each egg into a small cup, create a swirl, and gently slide egg in.',
      'Poach for 3-4 minutes until whites are set but yolks are runny.',
      'Spread avocado generously on toast.',
      'Top with poached eggs and sprinkle with chili flakes.',
    ],
    tips: [
      'Fresh eggs poach better — they hold their shape.',
      'Add a squeeze of lime for a tropical twist.',
      'Try everything bagel seasoning instead of chili flakes.',
    ],
  },
  {
    id: '3',
    title: 'Berry Açaí Smoothie Bowl',
    description: 'A vibrant, thick smoothie bowl loaded with fresh fruit, granola, and superfood toppings.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=500&h=300&fit=crop',
    cookingTime: 10,
    servings: 2,
    difficulty: 'easy',
    category: 'breakfast',
    ingredients: [
      { name: 'Frozen açaí packets', amount: '2' },
      { name: 'Frozen mixed berries', amount: '150g' },
      { name: 'Banana', amount: '1' },
      { name: 'Almond milk', amount: '120ml' },
      { name: 'Granola', amount: '60g' },
      { name: 'Fresh strawberries', amount: '6' },
      { name: 'Chia seeds', amount: '1 tbsp' },
      { name: 'Honey', amount: '1 tbsp' },
    ],
    instructions: [
      'Break açaí packets into pieces and add to blender.',
      'Add frozen berries, banana, and almond milk.',
      'Blend until thick and smooth (should be thicker than a smoothie).',
      'Pour into bowls.',
      'Arrange granola, sliced strawberries, and chia seeds on top.',
      'Drizzle with honey and serve immediately.',
    ],
    tips: [
      'Use as little liquid as possible for a thick, scoopable texture.',
      'Freeze banana slices beforehand for an even thicker bowl.',
      'Add a scoop of protein powder for extra nutrition.',
    ],
  },
  {
    id: '4',
    title: 'Classic French Omelette',
    description: 'A silky, perfectly folded French omelette with fresh herbs, gruyère cheese, and mushrooms.',
    image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=500&h=300&fit=crop',
    cookingTime: 12,
    servings: 1,
    difficulty: 'medium',
    category: 'breakfast',
    ingredients: [
      { name: 'Eggs', amount: '3' },
      { name: 'Butter', amount: '15g' },
      { name: 'Gruyère cheese (grated)', amount: '30g' },
      { name: 'Mushrooms (sliced)', amount: '50g' },
      { name: 'Fresh chives', amount: '1 tbsp' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Whisk eggs with a pinch of salt until fully blended.',
      'Sauté mushrooms in a little butter until golden, set aside.',
      'Melt butter in a non-stick pan over medium-low heat.',
      'Pour in eggs and gently stir with a spatula while shaking the pan.',
      'When eggs are mostly set but still slightly wet on top, add cheese and mushrooms.',
      'Fold omelette in thirds and slide onto plate.',
      'Garnish with fresh chives.',
    ],
    tips: [
      'Low heat is the secret — don\'t rush it.',
      'The center should be slightly creamy when you fold.',
      'Use a well-seasoned or non-stick pan for best results.',
    ],
  },

  // ── LUNCH ──
  {
    id: '5',
    title: 'Mediterranean Quinoa Bowl',
    description: 'A hearty grain bowl with roasted vegetables, feta, hummus, and a tangy lemon dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=300&fit=crop',
    cookingTime: 30,
    servings: 2,
    difficulty: 'easy',
    category: 'lunch',
    ingredients: [
      { name: 'Quinoa', amount: '200g' },
      { name: 'Cherry tomatoes', amount: '200g' },
      { name: 'Cucumber', amount: '1' },
      { name: 'Red onion', amount: '1/2' },
      { name: 'Kalamata olives', amount: '80g' },
      { name: 'Feta cheese', amount: '100g' },
      { name: 'Hummus', amount: '4 tbsp' },
      { name: 'Lemon-olive oil dressing', amount: '3 tbsp' },
    ],
    instructions: [
      'Cook quinoa according to package directions and let cool slightly.',
      'Halve cherry tomatoes and dice cucumber.',
      'Thinly slice red onion.',
      'Divide quinoa between bowls.',
      'Arrange tomatoes, cucumber, onion, and olives over quinoa.',
      'Crumble feta on top and add a dollop of hummus.',
      'Drizzle with lemon-olive oil dressing.',
    ],
    tips: [
      'Toast quinoa in a dry pan before cooking for a nutty flavor.',
      'Make extra quinoa for meal prep throughout the week.',
      'Add grilled chicken or chickpeas for more protein.',
    ],
  },
  {
    id: '6',
    title: 'Thai Green Curry',
    description: 'A vibrant and aromatic Thai curry with creamy coconut milk and fresh vegetables.',
    image: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?auto=format&fit=crop&q=80&w=800',
    cookingTime: 35,
    servings: 4,
    difficulty: 'medium',
    category: 'lunch',
    ingredients: [
      { name: 'Chicken breast', amount: '500g' },
      { name: 'Coconut milk', amount: '400ml' },
      { name: 'Thai green curry paste', amount: '3 tablespoons' },
      { name: 'Bell peppers', amount: '2' },
      { name: 'Thai basil leaves', amount: '1 handful' },
      { name: 'Fish sauce', amount: '2 tablespoons' },
      { name: 'Sugar', amount: '1 teaspoon' },
      { name: 'Lime juice', amount: '2 tablespoons' },
    ],
    instructions: [
      'Cut chicken into bite-sized pieces.',
      'Heat coconut milk in a large pan over medium heat.',
      'Add curry paste and stir until fragrant (about 2 minutes).',
      'Add chicken pieces and cook until done (8-10 minutes).',
      'Add bell peppers and cook for 5 more minutes.',
      'Season with fish sauce, sugar, and lime juice.',
      'Add Thai basil leaves at the end.',
      'Serve over jasmine rice.',
    ],
    tips: [
      'Don\'t skip the fish sauce - it adds authentic flavor.',
      'You can adjust the curry paste amount based on your heat preference.',
      'Add vegetables in stages based on cooking time.',
    ],
  },
  {
    id: '7',
    title: 'Crispy Chicken Caesar Wrap',
    description: 'Crunchy romaine, seasoned chicken, parmesan, and creamy Caesar dressing in a toasted tortilla.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=500&h=300&fit=crop',
    cookingTime: 25,
    servings: 2,
    difficulty: 'easy',
    category: 'lunch',
    ingredients: [
      { name: 'Chicken breast', amount: '2' },
      { name: 'Large flour tortillas', amount: '2' },
      { name: 'Romaine lettuce', amount: '2 cups' },
      { name: 'Parmesan cheese', amount: '40g' },
      { name: 'Caesar dressing', amount: '4 tbsp' },
      { name: 'Croutons', amount: '1/2 cup' },
      { name: 'Olive oil', amount: '1 tbsp' },
    ],
    instructions: [
      'Season chicken breasts with salt, pepper, and garlic powder.',
      'Grill or pan-fry chicken until cooked through (6-7 min per side).',
      'Let chicken rest 5 minutes, then slice thinly.',
      'Warm tortillas in a dry pan for 30 seconds each side.',
      'Chop romaine and toss with Caesar dressing.',
      'Layer dressed lettuce, sliced chicken, parmesan, and croutons on tortilla.',
      'Fold bottom up, then roll tightly from the side.',
    ],
    tips: [
      'Pound chicken to even thickness for uniform cooking.',
      'Toast the wrap in a pan seam-side down for extra crunch.',
      'Add anchovies to the dressing for an authentic Caesar flavor.',
    ],
  },
  {
    id: '8',
    title: 'Homemade Pizza Margherita',
    description: 'Make your own pizza from scratch with crispy crust and fresh toppings.',
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500&h=300&fit=crop',
    cookingTime: 45,
    servings: 2,
    difficulty: 'medium',
    category: 'lunch',
    ingredients: [
      { name: 'All-purpose flour', amount: '300g' },
      { name: 'Yeast', amount: '7g' },
      { name: 'Warm water', amount: '200ml' },
      { name: 'Salt', amount: '7g' },
      { name: 'Olive oil', amount: '20ml' },
      { name: 'Tomato sauce', amount: '200ml' },
      { name: 'Fresh mozzarella', amount: '200g' },
      { name: 'Fresh basil', amount: '1 bunch' },
    ],
    instructions: [
      'Mix warm water with yeast and let sit for 10 minutes.',
      'Combine flour and salt in a bowl.',
      'Add yeast mixture and olive oil to flour.',
      'Knead for 10 minutes until smooth and elastic.',
      'Let dough rise for 1 hour until doubled.',
      'Divide dough in half and shape into pizzas.',
      'Spread tomato sauce on each pizza.',
      'Top with mozzarella cheese.',
      'Bake at 220°C for 15-20 minutes until crust is golden.',
      'Add fresh basil after baking.',
    ],
    tips: [
      'Use a pizza stone for crispier crust.',
      'Don\'t overload with toppings.',
      'Oven temperature is crucial for good pizza.',
    ],
  },

  // ── DINNER ──
  {
    id: '9',
    title: 'Grilled Salmon with Lemon Butter',
    description: 'A restaurant-quality salmon dish with a delicate lemon butter sauce and fresh dill.',
    image: 'https://images.unsplash.com/photo-1580959375944-abd7e991f971?w=500&h=300&fit=crop',
    cookingTime: 30,
    servings: 2,
    difficulty: 'easy',
    category: 'dinner',
    ingredients: [
      { name: 'Salmon fillets', amount: '2 (6 oz each)' },
      { name: 'Butter', amount: '50g' },
      { name: 'Fresh lemon juice', amount: '2 tablespoons' },
      { name: 'Garlic cloves', amount: '2' },
      { name: 'Fresh dill', amount: '1 tablespoon' },
      { name: 'Salt and pepper', amount: 'to taste' },
      { name: 'Olive oil', amount: '2 tablespoons' },
    ],
    instructions: [
      'Preheat grill to medium-high heat.',
      'Pat salmon dry and season with salt and pepper.',
      'Brush grill grates with olive oil.',
      'Grill salmon skin-side down for 6-8 minutes.',
      'Flip and grill for another 4-5 minutes.',
      'In a small pan, melt butter and sauté minced garlic.',
      'Add lemon juice and dill to butter sauce.',
      'Drizzle sauce over salmon and serve.',
    ],
    tips: [
      'Don\'t flip the salmon too often - it needs time to develop a nice crust.',
      'You can also cook this in a pan if you don\'t have a grill.',
      'Watch the internal temperature - it should reach 145°F.',
    ],
  },
  {
    id: '10',
    title: 'Classic Margherita Pasta',
    description: 'A simple yet elegant Italian pasta dish with fresh tomatoes, basil, and mozzarella.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=300&fit=crop',
    cookingTime: 20,
    servings: 4,
    difficulty: 'easy',
    category: 'dinner',
    ingredients: [
      { name: 'Fresh pasta', amount: '400g' },
      { name: 'Fresh tomatoes', amount: '500g' },
      { name: 'Fresh mozzarella', amount: '250g' },
      { name: 'Fresh basil', amount: '1 bunch' },
      { name: 'Olive oil', amount: '4 tablespoons' },
      { name: 'Garlic cloves', amount: '2' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Bring a large pot of salted water to boil.',
      'Cut tomatoes in half and remove excess seeds.',
      'Heat olive oil in a pan and sauté minced garlic.',
      'Add tomatoes to the pan and cook for 10 minutes on medium heat.',
      'Cook pasta according to package directions until al dente.',
      'Drain pasta and toss with the tomato sauce.',
      'Top with fresh mozzarella and basil.',
      'Drizzle with olive oil and serve immediately.',
    ],
    tips: [
      'Use San Marzano tomatoes for the best flavor.',
      'Add pasta water to the sauce if it\'s too thick.',
      'Fresh basil should be added at the last moment for maximum flavor.',
    ],
  },
  {
    id: '11',
    title: 'Chocolate Lava Cake',
    description: 'A decadent dessert with a molten chocolate center — the perfect dinner finale.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&h=300&fit=crop',
    cookingTime: 25,
    servings: 2,
    difficulty: 'hard',
    category: 'dinner',
    ingredients: [
      { name: 'Dark chocolate', amount: '150g' },
      { name: 'Butter', amount: '100g' },
      { name: 'Eggs', amount: '2' },
      { name: 'Sugar', amount: '50g' },
      { name: 'Flour', amount: '25g' },
      { name: 'Vanilla extract', amount: '1 teaspoon' },
      { name: 'Pinch of salt', amount: '1 pinch' },
    ],
    instructions: [
      'Preheat oven to 220°C (425°F).',
      'Chop chocolate and place in a heatproof bowl with butter.',
      'Heat over simmering water until melted and smooth.',
      'In another bowl, whisk eggs with sugar until pale.',
      'Fold chocolate mixture into egg mixture.',
      'Gently fold in flour, vanilla, and salt.',
      'Pour into prepared ramekins.',
      'Bake for 12-14 minutes until the cake is set but the center is still soft.',
      'Let cool for 2 minutes, then invert onto plates.',
    ],
    tips: [
      'The centers should still be liquid - timing is crucial!',
      'Butter and flour the ramekins well to prevent sticking.',
      'You can prepare the batter in advance and refrigerate until ready to bake.',
    ],
  },
  {
    id: '12',
    title: 'Herb-Crusted Rack of Lamb',
    description: 'Tender rack of lamb with a fragrant herb crust, roasted to perfection and served with minted peas.',
    image: 'https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=500&h=300&fit=crop',
    cookingTime: 50,
    servings: 4,
    difficulty: 'hard',
    category: 'dinner',
    ingredients: [
      { name: 'Rack of lamb', amount: '2 racks (8 ribs each)' },
      { name: 'Dijon mustard', amount: '3 tbsp' },
      { name: 'Fresh rosemary', amount: '2 tbsp' },
      { name: 'Fresh thyme', amount: '1 tbsp' },
      { name: 'Garlic cloves', amount: '4' },
      { name: 'Breadcrumbs', amount: '80g' },
      { name: 'Olive oil', amount: '3 tbsp' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Preheat oven to 200°C (400°F).',
      'Season lamb racks generously with salt and pepper.',
      'Sear lamb in a hot pan with olive oil until browned on all sides.',
      'Mix breadcrumbs with minced rosemary, thyme, and garlic.',
      'Brush seared lamb with Dijon mustard.',
      'Press herb-breadcrumb mixture firmly onto mustard-coated lamb.',
      'Place on a roasting rack and roast for 20-25 minutes for medium-rare.',
      'Rest for 10 minutes before carving between ribs.',
    ],
    tips: [
      'Bring lamb to room temperature before cooking for even doneness.',
      'Use a meat thermometer: 57°C for medium-rare.',
      'Let the lamb rest — this redistributes the juices.',
    ],
  },
];